[package]
name = "mfek-ipc"
version = "0.0.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]
description = "Modular Font Editor K (MFEK) inter-process communication library."
edition = "2018"

[dependencies]
# Logging
csv = "1.1"
log = "0.4"

[dev-dependencies]
test-env-log = "0.2"
env_logger = "*"
